
#web.xml, root-context.xml, servlet-context.xml의 합본
#application.yml

server:
  port: 8585
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_1013?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: false
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
     
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 969334035410-32gu32bbaun4imvs0g7cbu6c89q947ep.apps.googleusercontent.com
            client-secret: c4fUAoJzzljcq4xREDmktfh5
            scope:
            - email
            - profile
